### ISSUE TITLE
Multicolor for axis text 

### ISSUE THREAD

**Issue by sharvarinarendra** [juba/scatterD3#88]
Hi! I wanted to give different colors to the axis text labels (depending on the label). I was wondering if it was possible to include this feature? Thanks!

**Comment by juba** [comment]
You mean the two labels corresponding to each axis, not the ticks label ?
Do you use `scatterD3` inside an Rmarkdown or shiny app ? Or do you use it directly inside RStudio ?

**Comment by sharvarinarendra** [comment]
I meant the tick labels. I’m using it in an RShiny App. I was also
wondering about a small issue with the developmental version of the package
- the tooltip disappears if I use the developmental version.

**Comment by juba** [comment]
Changing the tick labels color depending on their value is not possible. Axes are manged d3, and to my knowledge this features does not exist in this library.

And yes, you're right about the tooltips, I'll take a look at it.

**Comment by sharvarinarendra** [comment]
Okay, thanks a lot for all your help, I truly appreciate it! 😊

**Comment by juba** [comment]
I think the tooltips should now be fixed in the dev version. Don't hesitate to let me know if that is not the case.

You're welcome, and thanks to you for taking the time to report issues !

**Comment by sharvarinarendra** [comment]
Thank you! I’ll look into it and get back to you if I have any questions or
if I’m still facing issues.

**Comment by juba** [comment]
Thanks ! I close the issue for now, but don't hesitate to reopen it if needed.
